### ISSUE TITLE
RiboSTAMP analysis details

### ISSUE THREAD

**Issue by ilyes495** [JamesEttles/Translation-efficiency-driven-by-CNOT3-subunit-of-the-CCR4-NOT-complex-promotes-leukemogenesis#1]
Thank you for sharing the code for this great paper! 

I have been trying to reproduce the results of RiboSTAMP analysis, specifically the EPKM volcano plot in Figure 5K, however, I wasn't able to get the same results. I followed the steps you described as much as I could, but the volcano plot was way different. 

I would like to ask if it is possible to share the code for the RiboSTAMP part of the analysis. Thank you

**Comment by ilyes495** [comment]
Just to give more details. I followed the steps as described in the paper. first, I trimmed the adapters (copied from the repo), align the reads to hg38 using STAR. then I run sailor to obtain the edited sites, then I aggregated the edited sites across the replicates and filter sites occurring in less than two replicates, the resulting number of edits is similar to what you have reported in the paper, as shown here:

<img width="837" alt="Screenshot 2024-09-20 at 4 39 43 PM" src="https://github.com/user-attachments/assets/86157a69-9ca7-4257-b046-ec1880600e0f">

Then I calculated EPKM as in [RiboSTAMP paper](https://github.com/YeoLab/Yeo_STAMP_Nature_Methods/blob/main/figures/figure2/Fig2H_S2_epkm_quartiles_torin_riboseq2_old_experiment_reps_combined_w_scatters.ipynb), finally I inputted the resulting EPKMs to limma to perform differential EPKM analysis. 

The correlation between the log2fc of what I found and what reported here was very low and the same thing with padj. I would really appreciate it if you can help me figure out where I made a mistake.

**Comment by JamesEttles** [comment]
Hi Ilyes,

I apologise for the late reply.

I'm afraid I wasn't part of the Ribostamp analysis and the published code relates to Supplemental Figure 5A -5J and Figure 5A- 5G.

In brief I used Cutadapt to trim the reads and then aligned using RSEM, after which I did differential expression using DESeq2 to obtain an "upregulated" and "downregulated" group. From there I did gradient boosting to try and make a model that could understand the features of transcripts regulated by CNOT3 and confirmed by plotting the features of these transcripts.

I'd recommend getting in contact with Ly Vu if you want to learn more about the RiboStamp analysis.

Here is her email: ***@***.***
I hope this helps!
Best wishes,
James


________________________________

**Comment by ilyes495** [comment]
Thank you James for your reply! I will get in touch with Ly Vu for more details regarding RiboStamp analysis

Best,
Ilyes
